In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [3]:
#A is a sparse matrix
A= np.array([[1,0,0,0,0,0],
             [0,0,0,3,1,0],
             [0,0,0,0,0,1],
             [1,0,0,0,0,0]
             ])
print(A)

[[1 0 0 0 0 0]
 [0 0 0 3 1 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]]


In [4]:
S= csr_matrix(A) #compressed sparse matrix form
print(S)

  (0, 0)	1
  (1, 3)	3
  (1, 4)	1
  (2, 5)	1
  (3, 0)	1


In [5]:
print(type(S))

<class 'scipy.sparse._csr.csr_matrix'>


In [6]:
B= S.todense()
print(B)

[[1 0 0 0 0 0]
 [0 0 0 3 1 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]]
